macos_path: '/Users/mb/code/abjad-sled/data'
debian_path: '/home/t5h0qo/code/poc/abjad-sled/data'
port: 7001
domain: '127.0.0.1'
static_files_path: 'files'
decay_rate_factor_correct: 0.0 # 0.0 no decay
decay_rate_factor_incorrect: 0.0